### PR TITLE
Add hook for adding capabilities to ping on iputils upgrade

### PR DESCRIPTION
**Pull request by harryyoud**

### CODE REVIEW

**Comment by yuk7** [comment]
Thank you for your contribution.

But If I remember correctly, tar doesn't maintain Capability, so I don't think it will work in the environment before running `pacman-Syu`.

**Comment by harryyoud** [comment]
The bigger frustration is that we shouldn't need this at all, since the kernel should allow any user to ping. Sysctl isn't read at boot in WSL2 (since systemd doesn't run), which would normally set `net.ipv4.ping_group_range`. Do you know if there's any way to run commands at boot of the WSL2 VM?

**Comment by yuk7** [comment]
I think there is a way to use `bashrc`.
But I don't think it's a clean method.

**Comment by harryyoud** [comment]
Then I guess instead of capabilities, we need to use setuid bit in the hook. Otherwise, the bit is cleared on upgrade to iputils.

**Comment by yuk7** [comment]
(I may be wrong, but when I update the package with pacman, the package is unpacked with a tar that corresponds to the extended attributes, so I feel like it worked correctly after iputils was updated.

**Comment by harryyoud** [comment]
The capability used to happen as per https://github.com/archlinux/svntogit-packages/blob/packages/iputils/trunk/iputils.install, but is now intentionally skipped (by removing the reference to the post-install script in PKGBUILD) in favour of `/usr/lib/sysctl.d/50-default.conf` shipped with systemd, which sets `net.ipv4.ping_group_range` to all users, so no escalation of privilege is needed to send pings.

The capabilities were removed in this commit: https://github.com/archlinux/svntogit-packages/commit/8d9211dcdec1372a00b98bb2ebda2fe8fa313aa7

Setuid stopped being shipped with this commit: https://github.com/archlinux/svntogit-packages/commit/aca6affcf0fccc98257b296f69695507600b8b0e

This all means ping is shipped with no capabilities and no setuid bit. Since sysctl.d isn't processed on WSL, we need to set one of these. 

The extended attributes storing capabilities are present in the base targz downloaded, so we could just extract these. Then if we add cap to ping during the package update step, then compress with `--xattrs --xattrs-include="security.capabilities"` (which will preserve extended attributes), `wsl --import` should import these too. This also has the added benefit of keeping the capabilities present on `newgidmap` and `newuidmap`.

This appears to work well on WSL1 and WSL2; extended attributes stored in the targz are extracted to the root file system correctly, preserving capabilities.

**Review by yuk7 — APPROVED** [review]

**Comment by yuk7** [comment]
I sorry for making you go through the trouble of explaining it to me.
I wasn't aware of the changes made in 2020.

Thank you so much for your contribution!🙏

**Pull request merged**
